name: flutter_onboarding_screen
description: A flutter package which help developer in creating a onboarding screens of their app.

version: 2.0.2
homepage: https://github.com/champ96k/flutter-onboarding-screen

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: